### ISSUE TITLE
URL with parameters

### ISSUE THREAD

**Issue by picks44** [endroid/EndroidQrCodeBundle#17]
Hello,

How do I pass a URL with parameters to your twig extension ? So far it displays ```<img src="http://www.mydomain.com/foo.png?id=123" />``` which doesn't work :/
Or I'm missing something...

Thank you !

**Comment by davidromani** [comment]
@picks44 can you write how do you use the twig exetension?

**Comment by endroid** [comment]
Hi @picks44 it is not possible to pass a URL to the twig extension. It will always use a path relative to the host name of your application. The readme shows some examples of using the Twig extension.
