### ISSUE TITLE
Broken compatibility with symfony ~2.6

### ISSUE THREAD

**Issue by rakhnin** [endroid/EndroidQrCodeBundle#20]
By updating composer.json in tag 1.5.2: "symfony/http-kernel": "~2.7" you've made this project incompatible with previous versions of symfony (e.g. 2.6)

**Comment by endroid** [comment]
Hi @rakhnin, thank you for noticing. I agee this requirement is too strict and changed it to ~2.3 in 1.5.3. I hope that solves your problem.

**Comment by rakhnin** [comment]
Thank you.
