### ISSUE TITLE
Fix the composer.json endroid\QrCode requirements for V. 1.5.*

### ISSUE THREAD

**Issue by sentenza** [endroid/EndroidQrCodeBundle#25]
I have installed Endroid/QrCode with the default composer.json. But composer.phar has installed the [v. 1.1.2](https://github.com/endroid/QrCode/releases/tag/1.1.2), which doesn't have the `getDataUri()` method. 

After forcing the installation of QrCode v. 1.5.7 in composer.json, which requires php-gd, it will works as expected.

**Comment by endroid** [comment]
Hi @sentenza. Good to read you found a solution to your problem. The constrains are indeed a bit loose. The latest release of this bundle now requires a version >= 1.5.7 of the library so all features used in the bundle up to now are guaranteed to be present.
