### ISSUE TITLE
Compatibility Symfony 3

### ISSUE THREAD

**Issue by DevCG** [endroid/EndroidQrCodeBundle#27]
Hi,

I'm using your Qr code bundle and it appear that it is not fully compatible with Symfony 3.
I'm running 2.8.4-DEV and getting this deprecated warning :

```
The hardcoded value you are using for the $referenceType argument of the Symfony\Component\Routing\Generator\UrlGenerator::generate method is deprecated since version 2.8 and will not be supported anymore in 3.0. Use the constants defined in the UrlGeneratorInterface instead. (7 times)

    UrlGenerator::doGenerate() (called from appDevUrlGenerator.php at line 210)
    appDevUrlGenerator::generate() (called from classes.php at line 1284)
    Router::generate() (called from QrCodeExtension.php at line 102)
    QrCodeExtension::qrcodeUrlFunction() (called from classes.php(3256) : eval()'d code at line 55) ****
```
It can be solved by replacing in QrCodeExtension > qrcodeUrlFunction() l.102
`
return $this->container->get('router')->generate('endroid_qrcode', $params, true);`

Into : 

`return $this->container->get('router')->generate('endroid_qrcode', $params, UrlGeneratorInterface::ABSOLUTE_PATH);`

and adding 
`use Symfony\Component\Routing\Generator\UrlGeneratorInterface;`

**Comment by endroid** [comment]
Hi @DevCG, thank you for noticing. I adjusted this behavior in version 1.6.4.
