### ISSUE TITLE
Missing trait Symfony\Component\DependencyInjection\ContainerAwareTrait

### ISSUE THREAD

**Issue by moroine** [endroid/EndroidQrCodeBundle#28]
Hi,

I had an issue on the new release when I run `app/console cache:clear`

Here is the message error

> PHP Fatal error:  Trait 'Symfony\Component\DependencyInjection\ContainerAwareTrait' not found in vendor/endroid/qrcode-bundle/src/Twig/Extension/QrCodeExtension.php on line 22

Thank You !

**Comment by endroid** [comment]
Thank you for noticing. I just added the requirement for the DI component so it requires the correct version when you run composer install. I added the ContainerAwareTrait to Symfony in 2.4.0 so that will be the minimum version.
