### ISSUE TITLE
router, twig need default Parameter

### ISSUE THREAD

**Issue by ForeverGlory** [endroid/EndroidQrCodeBundle#29]
hi.
  twig.extension {{ qrcode_data_uri }} have default parameter, i think {{ qrcode_url }} and router.endroid_qrcode also need. So qrcode generated is unified.

**Comment by Bukashk0zzz** [comment]
Have same problem with qrcode_url.
Always need write extension option for now. {{ qrcode_url('test', {'extension': 'png'}) }}

**Comment by endroid** [comment]
@Bukashk0zzz The route parameters is now passed implicitly. @ForeverGlory the controller handling the URL generated by qrcode_url currently merges the URL parameters with the defaults determined in the factory.
