### ISSUE TITLE
Please provide an Upgrade.txt for the new major release.

### ISSUE THREAD

**Issue by Sander-Toonen** [endroid/EndroidQrCodeBundle#32]
A new major version, 2.x has been released. According to semantic versioning this implies that there are backward incompatible changes. However I can't find any information about whether or not I need to make any changes in order to be able to use the new version. Is the 2.x version is backward compatible? Could you otherwise please provide an upgrade path in an Upgrade.txt file?

**Comment by endroid** [comment]
Hi @Sander-Toonen I added a small description to the tag for you (https://github.com/endroid/EndroidQrCodeBundle/releases/tag/2.0.0). Mainly the new release is a refactoring to reduce a lot of duplicate parameters passing code and only the qrcode_url and qrcode_data_uri have changed. Now these functions accept an options array.

**Comment by Sander-Toonen** [comment]
Thanks!
