### ISSUE TITLE
php 5.3.* use trait

### ISSUE THREAD

**Issue by retamia** [endroid/EndroidQrCodeBundle#33]
class QrCodeExtension extends Twig_Extension implements ContainerAwareInterface
{
    use ContainerAwareTrait;
    //...
}

**Comment by zelding** [comment]
This seems to be a real issue, the composer.json only requires  PHP 5.3, but traits were introduced in 5.4. @endroid you should fix that ;)

**Comment by endroid** [comment]
Hi @retamia thank you. I updated the requirements.
