### ISSUE TITLE
In need of a new location to save generated QR codes

### ISSUE THREAD

**Issue by bahbzz** [endroid/EndroidQrCodeBundle#35]
I have been working with the generator for a while, i am using it with the Laravel framework. i need help concerning the location where generated qrcodes are saved. its saved in the public folder, but i need it to be saved in a different folder inside the public folder.

All help is appreciated

**Comment by endroid** [comment]
Hi @bahbzz in version 2.x of the library you can use the writeFile method to save to a specific path.
The readme of https://github.com/endroid/QrCode gives an example.

FYI this bundle is abandoned and will be removed soon so please post any following questions there.
