### ISSUE TITLE
Uncaught Error: Class 'Endroid\QrCode\ErrorCorrectionLevel' not found in

### ISSUE THREAD

**Issue by crazymaxim** [endroid/EndroidQrCodeBundle#82]
```
{
    "require": {
        "endroid/qr-code": "^4.6"
    }
}
```

`require_once __DIR__ . '/vendor/autoload.php'`

`use Endroid\QrCode\ErrorCorrectionLevel; `

`$qrCode->setErrorCorrectionLevel(ErrorCorrectionLevel::LOW); `

No matter what I try, an error occurs:
Uncaught Error: Class 'Endroid\QrCode\ErrorCorrectionLevel' not found in
Help me fix it. Thank you!

**Comment by endroid** [comment]
Hi @crazymaxim I think you are looking at the current readme while using an older version. You can consult the 4.6.0 readme and related error correction level handling at https://github.com/endroid/qr-code/tree/4.6.0. Good luck!
